swagger: "2.0"
info:
  version: 1.0.0
  title: techknights-website
  description: Backend to support the TechKnights website
basePath: /api
tags:
  - name: Examples
    description: Simple example endpoints
  - name: Specification
    description: The swagger API specification

consumes:
  - application/json
produces:
  - application/json


definitions:
  ExampleBody:
    type: object
    title: example
    required:
      - name
    properties:
      name:
        type: string
        example: no_stress

paths:
  /hello:
    get:
      tags:
        - Testing
      responses:
        description: Returns the string 'Hello, World!'

  /spec:
    get:
      tags:
        - Specification
      responses:
        200:
          description: Return the API specification
